/**
 * This code is automatically generated by scripts/singularity.py
 */

#include <cassert>
#include <vector>

#include "forward_declaration_singularity.h"

namespace nanospline {
namespace internal {


#if defined(HIGH_DEGREE_SUPPORT) || 2 < 5
#define Scalar double
template
std::vector<Scalar> compute_RationalBezier_degree_2_singularities(
        Scalar cx0, Scalar cy0, Scalar cx1, Scalar cy1, Scalar cx2, Scalar cy2,
        Scalar w0, Scalar w1, Scalar w2,
        Scalar t0,
        Scalar t1);
#undef Scalar

#if 2 < 10
#define Scalar float
template
std::vector<Scalar> compute_RationalBezier_degree_2_singularities(
        Scalar cx0, Scalar cy0, Scalar cx1, Scalar cy1, Scalar cx2, Scalar cy2,
        Scalar w0, Scalar w1, Scalar w2,
        Scalar t0,
        Scalar t1);
#undef Scalar
#endif
#endif


#if defined(HIGH_DEGREE_SUPPORT) || 3 < 5
#define Scalar double
template
std::vector<Scalar> compute_RationalBezier_degree_3_singularities(
        Scalar cx0, Scalar cy0, Scalar cx1, Scalar cy1, Scalar cx2, Scalar cy2, Scalar cx3, Scalar cy3,
        Scalar w0, Scalar w1, Scalar w2, Scalar w3,
        Scalar t0,
        Scalar t1);
#undef Scalar

#if 3 < 10
#define Scalar float
template
std::vector<Scalar> compute_RationalBezier_degree_3_singularities(
        Scalar cx0, Scalar cy0, Scalar cx1, Scalar cy1, Scalar cx2, Scalar cy2, Scalar cx3, Scalar cy3,
        Scalar w0, Scalar w1, Scalar w2, Scalar w3,
        Scalar t0,
        Scalar t1);
#undef Scalar
#endif
#endif


#if defined(HIGH_DEGREE_SUPPORT) || 2 < 5
#define Scalar double
template
std::vector<Scalar> compute_Bezier_degree_2_singularities(
        Scalar cx0, Scalar cy0, Scalar cx1, Scalar cy1, Scalar cx2, Scalar cy2,
        Scalar t0,
        Scalar t1);
#undef Scalar

#if 2 < 10
#define Scalar float
template
std::vector<Scalar> compute_Bezier_degree_2_singularities(
        Scalar cx0, Scalar cy0, Scalar cx1, Scalar cy1, Scalar cx2, Scalar cy2,
        Scalar t0,
        Scalar t1);
#undef Scalar
#endif
#endif


#if defined(HIGH_DEGREE_SUPPORT) || 3 < 5
#define Scalar double
template
std::vector<Scalar> compute_Bezier_degree_3_singularities(
        Scalar cx0, Scalar cy0, Scalar cx1, Scalar cy1, Scalar cx2, Scalar cy2, Scalar cx3, Scalar cy3,
        Scalar t0,
        Scalar t1);
#undef Scalar

#if 3 < 10
#define Scalar float
template
std::vector<Scalar> compute_Bezier_degree_3_singularities(
        Scalar cx0, Scalar cy0, Scalar cx1, Scalar cy1, Scalar cx2, Scalar cy2, Scalar cx3, Scalar cy3,
        Scalar t0,
        Scalar t1);
#undef Scalar
#endif
#endif


#if defined(HIGH_DEGREE_SUPPORT) || 4 < 5
#define Scalar double
template
std::vector<Scalar> compute_Bezier_degree_4_singularities(
        Scalar cx0, Scalar cy0, Scalar cx1, Scalar cy1, Scalar cx2, Scalar cy2, Scalar cx3, Scalar cy3, Scalar cx4, Scalar cy4,
        Scalar t0,
        Scalar t1);
#undef Scalar

#if 4 < 10
#define Scalar float
template
std::vector<Scalar> compute_Bezier_degree_4_singularities(
        Scalar cx0, Scalar cy0, Scalar cx1, Scalar cy1, Scalar cx2, Scalar cy2, Scalar cx3, Scalar cy3, Scalar cx4, Scalar cy4,
        Scalar t0,
        Scalar t1);
#undef Scalar
#endif
#endif


#if defined(HIGH_DEGREE_SUPPORT) || 5 < 5
#define Scalar double
template
std::vector<Scalar> compute_Bezier_degree_5_singularities(
        Scalar cx0, Scalar cy0, Scalar cx1, Scalar cy1, Scalar cx2, Scalar cy2, Scalar cx3, Scalar cy3, Scalar cx4, Scalar cy4, Scalar cx5, Scalar cy5,
        Scalar t0,
        Scalar t1);
#undef Scalar

#if 5 < 10
#define Scalar float
template
std::vector<Scalar> compute_Bezier_degree_5_singularities(
        Scalar cx0, Scalar cy0, Scalar cx1, Scalar cy1, Scalar cx2, Scalar cy2, Scalar cx3, Scalar cy3, Scalar cx4, Scalar cy4, Scalar cx5, Scalar cy5,
        Scalar t0,
        Scalar t1);
#undef Scalar
#endif
#endif


#if defined(HIGH_DEGREE_SUPPORT) || 6 < 5
#define Scalar double
template
std::vector<Scalar> compute_Bezier_degree_6_singularities(
        Scalar cx0, Scalar cy0, Scalar cx1, Scalar cy1, Scalar cx2, Scalar cy2, Scalar cx3, Scalar cy3, Scalar cx4, Scalar cy4, Scalar cx5, Scalar cy5, Scalar cx6, Scalar cy6,
        Scalar t0,
        Scalar t1);
#undef Scalar

#if 6 < 10
#define Scalar float
template
std::vector<Scalar> compute_Bezier_degree_6_singularities(
        Scalar cx0, Scalar cy0, Scalar cx1, Scalar cy1, Scalar cx2, Scalar cy2, Scalar cx3, Scalar cy3, Scalar cx4, Scalar cy4, Scalar cx5, Scalar cy5, Scalar cx6, Scalar cy6,
        Scalar t0,
        Scalar t1);
#undef Scalar
#endif
#endif


} // End internal namespace
} // End nanospline namespace

